---
title: "Untitled"
output: html_document
date: "2024-03-26"
---


## Search inline

```{r include=FALSE}
model <- udpipe::udpipe_load_model("/home/jtimm/pCloudDrive/nlp/udpipe-model/english-ewt-ud-2.5-191206.udpipe")
```


### Annotate corpus with `udpipe`

```{r}
ud_annotated_corpus <- udpipe::udpipe(
  object = model,
  x = tokens,
  tagger = "default",
  parser = "none"
)
```


```{r echo=FALSE}
ud_annotated_corpus |>
  select(doc_id, start:xpos) |>
  slice(1:5) |>
  knitr::kable()
```


### Build inline text

```{r message=FALSE, warning=FALSE}
inline_ss <- ud_annotated_corpus |>
  mutate(inline = paste0(token, "/", xpos, "/", token_id)) |>
  tidyr::separate(
    col = doc_id,
    into = c("doc_id", "sentence_id"),
    sep = "\\."
  ) |>
  group_by(doc_id, sentence_id) |>
  summarise(text = paste0(inline, collapse = " "))

inline_ss$text[1] |> strwrap(width = 55)
```


### Search for lexico-grammatical pattern

```{r}
inline_ss |>
  textpress::search_corpus(
    search = "JJ and JJ",
    highlight = c("<b>", "</b>"),
    n = 0,
    is_inline = T
  ) |>
  select(doc_id:text) |>
  filter(tokenizers::count_words(text) < 75) |>
  slice(3:4) |>
  ## DT::datatable(escape = F)
  knitr::kable(escape = F)
```

